<?php
/*
 * Plugin Name:       FastBots
 * Plugin URI:        https://wordpress.org/plugins/fastbots/
 * Description: Easily add your FastBots AI chatbot to your WordPress site.
 * Version:           1.0.14
 * Requires at least: 5.2
 * Requires PHP:      7.2
 * Author:            FastBots
 * Author URI:        https://fastbots.ai
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       fastbots-ai-chatbots
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

define( 'FASTBOTS_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );

require_once(FASTBOTS_PLUGIN_DIR . 'settings-page.php');

function fastbots_enqueue_chatbot_script() {
    $embed_url = get_option('fastbots_chatbot_embed_code');
    $bot_id    = get_option('fastbots_chatbot_embed_code_two');

    if ( empty( $embed_url ) || empty( $bot_id ) ) {
        return;
    }

    $safe_url = esc_url_raw( $embed_url );

    if ( empty( $safe_url ) ) {
        return;
    }

    // The remote FastBots service controls caching and updates for embed.js.
    wp_enqueue_script(
        'fastbots-chatbot',
        $safe_url,
        array(),
        null, // phpcs:ignore WordPress.WP.EnqueuedResourceParameters.MissingVersion
        false
    );
}

/**
 * Add the FastBots-specific attributes to the enqueued embed script.
 *
 * @param string $tag    The script tag generated by WordPress.
 * @param string $handle The registered script handle.
 * @return string
 */
function fastbots_add_chatbot_script_attributes( $tag, $handle ) {
    if ( 'fastbots-chatbot' !== $handle ) {
        return $tag;
    }

    $bot_id = get_option( 'fastbots_chatbot_embed_code_two' );

    if ( empty( $bot_id ) ) {
        return $tag;
    }

    return str_replace(
        ' src=',
        sprintf( ' defer data-bot-id="%s" src=', esc_attr( $bot_id ) ),
        $tag
    );
}

add_action( 'wp_enqueue_scripts', 'fastbots_enqueue_chatbot_script' );
add_filter( 'script_loader_tag', 'fastbots_add_chatbot_script_attributes', 10, 2 );
